package domain

const CRITICAL_DAMAGE_FACTOR float32 = 2
const MINIMUM_BASE_ATTRIBUTE_HEALTH float32 = 1
const MINIMUM_BASE_ATTRIBUTE_STAMINA float32 = 1
const MINIMUM_BASE_ATTRIBUTE_MANA float32 = 0
const MINIMUM_CHANCE float32 = 1
const MAXIMUM_CHANCE float32 = 100
